# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /dvereNovotny

# Title of the Site
title: Filip Novotný
# Description of the Site
description: Výroba oken a dveří
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Okna, dveře, Novotný, Velešín
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: novotny.f.72@seznam.cz
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
#github_username:  thedevslot
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Filip Novotný
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2013/07/13/10/07/man-156584_960_720.png
# 60 Words About the Author
author-about: V oboru se pohybuji již více než 20 let, mám za sebou mnoho úspěšných zakázek, jak pro velké firmy XXX YYY ZZZ, tak i pro malé podniky jako jsou .........  ale i jednotlivce. Pracuji po celé ČR atd atd atd tady něco doplnit
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://appfactory.cz
author-ico: 74171941
author-telefon: +420 777 163 708
author-adresa: U Přehrady 562, 382 32, Velešín
author-mapa: https://frame.mapy.cz/s/darunapoka

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

collections:
  - projects
# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
